### ISSUE TITLE
"Programming Sequence for DMP Hardware Functions"

### ISSUE THREAD

**Issue by mconsidine** [kriswiner/MPU9250#142]
Hi Kris,
The above document is referenced in some of the existing MPU-9250 docs as - it would appear - enabling quaternion output from the MPU-9250.  Have you explored any of the "advanced" functions that are referenced in the existing docs?
Thanks,
Matt

**Comment by kriswiner** [comment]
The MPU9250 DMP can only do 6 DoF fusion; 9 DoF fusion has to be dome on
the host MCU. I have used their 6 DoF fusion solution from the DMP but it
is not as good as even simple madwick fusion done on the host. See:

https://github.com/kriswiner/MPU-6050/wiki/Affordable-9-DoF-Sensor-Fusion

**Comment by mconsidine** [comment]
Okay, thanks.  I managed to get a copy of the above mentioned docs and was wondering how useful the "advanced" functions would be.
Matt

**Comment by kriswiner** [comment]
Can you send me a copy of the document(s) please?

**Comment by mconsidine** [comment]
Sent a pm to you on the pjrc site.

**Comment by kriswiner** [comment]
Please send it to me at tleracorp@gmail.com, thanks.

**Comment by mconsidine** [comment]
Email sent.

**Comment by kriswiner** [comment]
Thanks, I have seen most of these before but not the advanced features.

Too bad they don;t publish the firmware, I would like to try the tap
detection.

**Comment by phanhust09** [comment]
hi. i have project use MPU. so i want to find out more about DMP in MP 9250. so could you send me this document . thanks 
mail : lamhust09@gmail.com

**Comment by kriswiner** [comment]
Don't have it, ask Invensense.

**Comment by kriswiner** [comment]
Actually, I do. Send me a request at tleracorp@gmail.com.

**Comment by SeanStayn** [comment]
SparkFun has a firmware in the git: https://github.com/sparkfun/SparkFun_MPU-9250-DMP_Arduino_Library/blob/master/src/util/inv_mpu_dmp_motion_driver.c

At line 223.

Perhaps, it helps you.

**Comment by SeanStayn** [comment]
Additionally: In the datasheet from the MPU9250 on the page 54 is a hint, that a 9-axis quat. output is possible. 

https://cdn.sparkfun.com/assets/learn_tutorials/5/5/0/MPU-9250-Register-Map.pdf

It would be very cool to use the direct quat values. :)

**Comment by kriswiner** [comment]
Not with the MPU9250, not possible.

But with this, it is:

https://www.tindie.com/products/onehorse/ultimate-sensor-fusion-solution/?pt=ac_prod_search
