### ISSUE TITLE
error compiling MPU9250BasicAHRS_t3.ino

### ISSUE THREAD

**Issue by seamaster101** [kriswiner/MPU9250#160]
Hi Kris,

My goal is to create a rate compass that is tilt compensated for a boat autopilot reference. Any hints for that use?

thanks for the help  
Jordan

**Comment by seamaster101** [comment]
or I get error: "MadgwickQuaternionUpdate" was not declared in this scope, depending which line in the code I have enabled.

**Comment by kriswiner** [comment]
Looks like you forgot to include the quaternionFilters.ino file in your
sketch

**Comment by seamaster101** [comment]
thank you! this resolved that issue of mine. Sorry for the stupid question....
