### ISSUE TITLE
magnetometer data read at 100Hz

### ISSUE THREAD

**Issue by hassankord** [kriswiner/MPU9250#242]
Dear Kris
thanks for your code.
I notice that you defaulted your code to use  magnetometer data at 8 Hz
uint8_t Mmode = 0x02;        // 2 for 8 Hz, 6 for 100 Hz continuous magnetometer data read

I would like to use the 100Hz , 
does that make difference, is there a precaution or limitation that let you preferred the 8 Hz as default value.

Best Regards,
Hassan

**Comment by kriswiner** [comment]
For my application 8 Hz was appropriate. You can use 100 Hz at the cost of
some extra power expended.

**Comment by hassankord** [comment]
many thanks too
