### ISSUE TITLE
Yaw angle is not accurate!

### ISSUE THREAD

**Issue by clhne** [kriswiner/MPU9250#262]
hello kris,
thanks for such a wonderful library. I am using STM32F103C8T6 and i am using your library for reading the data from mpu9250. 
but,  i find the yaw angle is changed between -180~+180, so what's the problems? 
btw, i have calibrated the magnetometer, but the result don't look right:
![mag](https://user-images.githubusercontent.com/11884005/38462179-e5c9fa1c-3b14-11e8-9c41-168a8b53ba7b.png)
 
thank you.

**Comment by kriswiner** [comment]
Mag not calibrated, way off...

**Comment by clhne** [comment]
Hi, Kris.
I have calibrated the mag, and the result look like this:
![cal](https://user-images.githubusercontent.com/11884005/38482184-d8cd9d54-3c00-11e8-8876-3de88c26e4ff.png)

and I rotate the board, then I found a problem:
yaw angle is affected by pitch(when I rotate around the y axis):
![1](https://user-images.githubusercontent.com/11884005/38482277-2b2e9d6e-3c01-11e8-86a7-822864d19545.png)
after rotate: 
![2](https://user-images.githubusercontent.com/11884005/38482289-33fc6480-3c01-11e8-975d-ebb3729646bf.png)

so why ?
Thank you.

**Comment by kriswiner** [comment]
Are you passing data to the fusion filter as NED?

**Comment by clhne** [comment]
Yes, I reference the data sheet: 
acc and gyro as: 

![icm20602 orientation](https://user-images.githubusercontent.com/11884005/38530982-5464dd98-3ca0-11e8-9871-e6a121ca1061.png)

mag : 
![ak8975 orientation](https://user-images.githubusercontent.com/11884005/38530998-628720a2-3ca0-11e8-87ac-6e82b8a1f3d7.png)

and the fusion filter as: 
update(gyro[1], -gyro[0], -gyro[2], acc[1], -acc[0], -acc[2], mag[1], mag[0], mag[2]);
What may be the problem?

**Comment by kriswiner** [comment]
This is not an MPU9250...

**Comment by clhne** [comment]
Yes, it's a 6-axis motion tracking device that combines a 3-axis gyroscope, 3-axis accelerometer, along with AK8975 3-axis electronic compass.
so Mahony fusion filter can be used, isn't it?

**Comment by kriswiner** [comment]
both Madwick and Mohony filters take accel,gyro,mag input. Unless you
rerranged the functions, you are feeding gyro first...

**Comment by kriswiner** [comment]
both Madwick and Mahony filters take accel, gyro, mag input. Unless you
rerranged the functions, you are feeding gyro first...

How are the mag and accel/gyro aligned then?

**Comment by clhne** [comment]
The accel/gyro and mag aligned as: 
![icm20602 align](https://user-images.githubusercontent.com/11884005/38532198-48626028-3ca6-11e8-9efe-06c699f3e869.png)

**Comment by kriswiner** [comment]
Then this can't be correct... update(gyro[1], gyro[0], gyro[2], acc[1],
acc[0], acc[2], -mag[1], mag[0], -mag[2]);

Needs to be NED

**Comment by clhne** [comment]
What's the order ?
update(gyro[1], -gyro[0], -gyro[2], acc[1],-acc[0], -acc[2], mag[1], mag[0], mag[2]); right?

**Comment by kriswiner** [comment]
N E D

**Comment by clhne** [comment]
update(gyro[1], -gyro[0], -gyro[2], acc[1], -acc[0], -acc[2], mag[1], mag[0], mag[2])  ?
Thank you.

**Comment by kriswiner** [comment]
Why are you putting gyro data first? Mahony expects accel/gyor/mag
according to the function I wrote. Did you rewrite it to change the order?

**Comment by clhne** [comment]
The Mahony algorithm expects:
void MahonyAHRSupdate(float gx, float gy, float gz, float ax, float ay, float az, float mx, float my, float mz);
you can find in: http://x-io.co.uk/open-source-imu-and-ahrs-algorithms/ 
in "C code (Header and source files)"
So, why your function expects accel/gyro/mag ?

**Comment by kriswiner** [comment]
Just a matter of convention; it simply depends on which mahony function you
are using. I only mention this because it is different from mine, so if you
were using my sketch then it would be wrong.

**Comment by clhne** [comment]
Yeah, I use the source code not yours, and I reference the NED tutorial that you commented at : https://github.com/kriswiner/MPU9250/issues/257
I wonder if  (gx, -gy, -gz, ax, -ay, -az, -mx, -my, mz) is ok ?
