### ISSUE TITLE
If there is a Gimbal lock in RPY(Roll, Pitch, Yaw)?

### ISSUE THREAD

**Issue by clhne** [kriswiner/MPU9250#267]

**Comment by kriswiner** [comment]
Not sure what you mean...if you are using quaternions there should not be,
that is the whole point.

**Comment by clhne** [comment]
yeah, I use Mahony AHRS algorithm, but the result is represented as Euler angle(RPY), so if the Gimbal lock still exit?

**Comment by kriswiner** [comment]
Not supposed to
