### ISSUE TITLE
Sensor fusion algortim of the DMP MPU9250

### ISSUE THREAD

**Issue by PauwelsKristof** [kriswiner/MPU9250#282]
Hi Kris,

I have a small question, I am writing a thesis that involves the DMP of the MPU-9250 IMU of InvenSense. The question I would like to ask is the following: Is there somewhere any infomation on which algorithms InvenSense uses for the Sensor Fusion in the DMP? Do they use a kalman filter or something else?

Thanks,
Kristof

**Comment by kriswiner** [comment]
No one but Invensense knows.

**Comment by kriswiner** [comment]
Maybe you can guess from this:

https://github.com/kriswiner/MPU9250/blob/master/Documents/Application%20Note%20-%20Programming%20Sequence%20for%20DMP%20Hardware%20Functions%20v12%20(....pdf
