### ISSUE TITLE
Could not connect to MPU9250: 0xFF

### ISSUE THREAD

**Issue by John-Val** [kriswiner/MPU9250#58]
Hi Kris,
I try to use read data from a 9 dof which has written MPY 92/65 on the breakout board. On the back it has written 9250/9255/6500/6555.
So I think I should be able to use your example code. But testing it on two Arduino Uno's and with 3 different breakout boards I keep on getting:

Could not connect to MPU9250: 0xFF.

Both with or without the suggested alterations:
 We have disabled the internal pull-ups used by the Wire library in the Wire.h/twi.c utility file.
 We are also using the 400 kHz fast I2C mode by setting the TWI_FREQ  to 400000L /twi.h utility file.

The uno boards have separate SCL SDA pins. I used those but I also used A4 and A5 as in the sketch.
I use the 3.3 V power supply. 

Am I doing something wrong or did I just buy some useless plastic and ceramics?

I hope you can help me out.

**Comment by kriswiner** [comment]
If you bought the purple boards from China then yes, they are junk.

Make sure the SDA and SCL lines both show 3V3 with a voltmeter when powered on.

It is likely you don't have the I2C address of the MPU9250 right. It can be either 0x68 or 0x69. If you run an I2C scan, what do you get? Here's how:

 `
      // I2C scan function

```
 void I2Cscan()
 {
// scan for i2c devices
 byte error, address;
 int nDevices;

 Serial.println("Scanning...");

 nDevices = 0;
 for(address = 1; address < 127; address++ ) 
{
  // The i2c_scanner uses the return value of
   // the Write.endTransmisstion to see if
  // a device did acknowledge to the address.
  Wire.beginTransmission(address);
  error = Wire.endTransmission();

  if (error == 0)
  {
      Serial.print("I2C device found at address 0x");
    if (address<16) 
      Serial.print("0");
    Serial.print(address,HEX);
    Serial.println("  !");

    nDevices++;
 }
  else if (error==4) 
{
   Serial.print("Unknow error at address 0x");
   if (address<16) 
    Serial.print("0");
   Serial.println(address,HEX);
 }    
 }
  if (nDevices == 0)
  Serial.println("No I2C devices found\n");
  else
  Serial.println("done\n");

  }
```

`

**Comment by John-Val** [comment]
Dear Kris,
Thank you very much for your extremely quick response. Yes I did buy them in China, but tomorrow I certainly will try your other suggestions.
Sincerly yours,
John Val

**Comment by John-Val** [comment]
Hi Kris,
It seems I got it working.
The MPU9255 rc2 is on 0x68
Who Am I should return 73. 
I also forgot to change the intPin to 2.
Many thanks again for your help.

**Comment by sakshirawal14** [comment]
@kriswiner Hi
I am facing the same issue. I tried running the I2Cscan(), but the serial monitor shows no output whatsoever. How do I know if the address is correct in the code?

**Comment by kriswiner** [comment]
The serial monitor should at least show Scanning...

I think there is an error in your setup.

What is the voltage on SDA and SCL?

What MCU are you using?

Which pins are you using for SDA/SCL?

Does the board have power?

Which board are you using?

Can't help much without some more info.

**Comment by sakshirawal14** [comment]
Hi..I'm using the Arduino Uno and the MPU 9250. I have made the following connections
VDD---3.3V
GND---GND
SCL---A5
SDA---A4

**Comment by kriswiner** [comment]
Mpu9259 is 3v3 only; you need to use a logic level converter?

Do you have pullup resistors on the mpu9250 board?

**Comment by sakshirawal14** [comment]
It works on 3.3V. Haven't used it before but the forums and posta I have referrred to say that only the above 4 connections are needed for it to work. I'm not using any external pull-ups either.

**Comment by kriswiner** [comment]
What is the voltage on sda and scl?

You need pullups.

**Comment by sakshirawal14** [comment]
Will the voltage on SDA and SCL not be 3.3 V only? I don't have much hands on experience with thw hardware. How do I use pull-ups?

**Comment by kriswiner** [comment]
Connect a 10 kOhm resistor between 3V3 and SDA. Do the same for SCL.

**Comment by sakshirawal14** [comment]
Okay..thank you. Will do that and try running the code. Will get back to you then.

**Comment by sakshirawal14** [comment]
Okay..so the I2C scanner detects the device at 0x68.
But when I try to run the code, it says "MPU9250 connection failed"
Any idea..why?

**Comment by kriswiner** [comment]
Not without more info

**Comment by AcidPrank** [comment]
Hi kriswiner, and thank you very much for all what you did :) 

I'm facing a similar problem. It seems it appears when my Arduino Due reset.. When the MPU is found, it works very well and I get serial data for a while, no crash nothing, but when I close the serial monitor, and reopen it (I think it means that Arduino Due is restarted) then one every ~3-4, the MPU will not be found. Then I need to restart the Arduino IDE unplug my USB plug again, without warranty it works. 

Here is my wiring diagram, I use 2K resistors, do you think it's enough ? 
![plan_cablage_mpu9250](https://cloud.githubusercontent.com/assets/24197355/26316175/afbf1d7e-3f13-11e7-9162-840cbeb12ada.png)

**Comment by kriswiner** [comment]
Maybe too much, you have pullups already on the breakout no?

**Comment by AcidPrank** [comment]
yes I think this 1,5 k that's what I measured on SDA0 and SDA1 (20 and 21)

**Comment by kriswiner** [comment]
Looks like you have GND connected to 3V3 in your diagram too.

**Comment by BobarTrump** [comment]
oh ! it should be on the another one ? I didn't know about that ..

**Comment by kriswiner** [comment]
Huh?

**Comment by AcidPrank** [comment]
Excuse me, I didn't understand your sentence the first time. this is a mistake in my diagram but I didn't did it in real (fortunately !)... I tought you were saying me to change of GND ...  I removed the pullup resistors, It seems better now...

**Comment by AcidPrank** [comment]
I think I solved my problem, two things : 

first, I removed theses useless pullup resistors, that improved it. 
second, it happened again sometimes so I found that interesting link that described a problem really similar : 
https://github.com/esp8266/Arduino/issues/1025 

so I implemented the solution : 

```
void I2C_recovery() {
 Serial.println("Starting I2C bus recovery");
  delay(2000);
  int SDAPIN = 70;
  int CLKPIN = 71;
  //try i2c bus recovery at 100kHz = 5uS high, 5uS low
  pinMode(SDAPIN, OUTPUT);//keeping SDA high during recovery
  digitalWrite(SDAPIN, HIGH);
  pinMode(CLKPIN, OUTPUT);
  for (int i = 0; i < 10; i++) { //9nth cycle acts as NACK
    digitalWrite(CLKPIN, HIGH);
    delayMicroseconds(5);
    digitalWrite(CLKPIN, LOW);
    delayMicroseconds(5);
  }

  //a STOP signal (SDA from low to high while CLK is high)
  digitalWrite(SDAPIN, LOW);
  delayMicroseconds(5);
  digitalWrite(CLKPIN, HIGH);
  delayMicroseconds(2);
  digitalWrite(SDAPIN, HIGH);
  delayMicroseconds(2);
  //bus status is now : FREE

  Serial.println("bus recovery done, starting scan in 2 secs");
  //return to power up mode
  pinMode(SDAPIN, INPUT);
  pinMode(CLKPIN, INPUT);
  delay(2000);
  //pins + begin advised in https://github.com/esp8266/Arduino/issues/452
  //Wire1.pins(SDAPIN, CLKPIN); //this changes default values for sda and clock as well
  Wire1.begin();
  //only pins: no signal on clk and sda
  //only begin: no signal on clk, no signal on sda


  //no further processing in case of error
  /*
  while(true)
  {
    i2c_scan(); 
  }
  */
}
```

I'm using an Arduino Due with SDA1 and SCL1 that's why I use Wire1 ( and SDAPIN = 70 , CLKPIN = 71...)

And use it in the begining of my setup like this : 

```
 if (!I2Cscan()) {
    I2C_recovery();
    I2Cscan();
  }
```

I modified the I2C scan so it returns true if a device has been detected, false if this is not the case...

Looks like it helps :) 
```
Scanning...
No I2C devices found
Starting I2C bus recovery
bus recovery done, starting scan in 2 secs
Scanning...
I2C device found at address 0x0C  !
I2C device found at address 0x68  !
```

**Comment by sakshirawal14** [comment]
@kriswiner Hi..What info can I help you with?

**Comment by kriswiner** [comment]
No idea what your problem is

**Comment by sakshirawal14** [comment]
I2Cscanner detects the device at 0x68, but when I try to run my sketch to get raw data from the IMU, it says  "MPU9250 connection failed"
Also, I get 2 warning messages in the terminal window as:
Invalid library found in C:\Users\sakshi\Documents\Arduino\libraries\i2cdevlib-master: C:\Users\sakshi\Documents\Arduino\libraries\i2cdevlib-master
Invalid library found in C:\Users\sakshi\Documents\Arduino\libraries\i2cdevlib-master: C:\Users\sakshi\Documents\Arduino\libraries\i2cdevlib-master

**Comment by kriswiner** [comment]
Why use i2cdev? Maybe need to ask them?

**Comment by sakshirawal14** [comment]
I tried using your code, but it had some errors. So I just wanted to do a basic raw data read and check first.

**Comment by kriswiner** [comment]
OK,

What MCU are you using?

Which code did you try?

**Comment by sakshirawal14** [comment]
I'm using the Arduino Uno and trying to get the raw values using I2C

**Comment by kriswiner** [comment]
Try here: http://www.lucidarme.me/?p=5057

**Comment by John-Val** [comment]
To my knowledge MPU9250 is on 73. Try the MPU9150 library instead since is MPU9150 on 68.

John


________________________________
Van: Kris Winer <notifications@github.com>
Verzonden: dinsdag 23 mei 2017 08:53:19
Aan: kriswiner/MPU9250
CC: John Val; State change
Onderwerp: Re: [kriswiner/MPU9250] Could not connect to MPU9250: 0xFF (#58)

Try here: http://www.lucidarme.me/?p=5057

**Comment by kriswiner** [comment]
You can't use an MPU9150 library for the MPU9250, the register addresses
are different.

If you can get an ACK from the MPU9250 at I2C address 0x68, then what does
the WHO_AM_I register show? Should be 0x71 for the MPU9250 or 0x73 for the
MPU9255.

**Comment by Patrickyp** [comment]
Kris can you help me I'm trying to write high to the AD0/SDO pin of my sparkfun 9250 but the address is staying at 0x68 even though I made the pin high.   

my wiring.. 
https://i.imgur.com/jaw8rxF.jpg

```
void setup()
{
    Wire.begin();
    //  TWBR = 12;  // 400 kbit/sec I2C speed
    Serial.begin(38400);
    
    // Set up the interrupt pin, its set as active high, push-pull
    pinMode(intPin, INPUT);
    digitalWrite(intPin, LOW);
    pinMode(myLed, OUTPUT);
    digitalWrite(myLed, HIGH);
    
     //  I have pin 12 connected to AD0 and writing high (~3v)
    pinMode(12, OUTPUT);
    digitalWrite(12, HIGH);
    
    delay(2000);
    I2Cscan();

```

and returns 

Scanning...
I2C device found at address 0x68  !
done

MPU9250
9-DOF 16-bit
motion sensor
60 ug LSB
MPU9250 I AM FF I should be 71
Could not connect to MPU9250: 0xFF

![img_1763](https://user-images.githubusercontent.com/6183727/40454788-ddc79d26-5e85-11e8-9a4d-84aa75db5ef4.JPG)

**Comment by kriswiner** [comment]
Is pin 12 connected to ADO or not? Is pin 12 showing 3.3 V?

**Comment by MitalPattani** [comment]
@Patrickyp You need to soldier your sj2 centre pad to the right one for and then connect AD0 to 3v3 or gnd for 0×69 or 0×68 respectively. 
Check the sparkfun hookup guide for more information.

**Comment by Patrickyp** [comment]
@MitalPattani are you talking about the white little rectangle next to the square that looks like it has solder on it?  SHould I be connecting solder from the square to the the white rectangle?

**Comment by Patrickyp** [comment]
@kriswiner I checked it (ADO) once with a volt meter and it seems to be showing around 3v I will double check again when I get a chance to work on it again but it seems like the sparkfun board needs to have some connection to get the address switchin function that I missed from their guide like Mital mentioned.

**Comment by Patrickyp** [comment]
https://www.tindie.com/products/onehorse/ultimate-sensor-fusion-solution/#product-reviews

@kriswiner would you recommend buying this as alternative to the sparkfun mpu9250? I'm thinking of trying your version to see if it works well for me.

**Comment by kriswiner** [comment]
This has both the MPU9250 (in a better design than that offered by
Sparkfun) and the EM7180 motion co-processor. With the latter, you can read
quaternions or Euler angles (yaw, pitch, roll) directly from the EM7180 via
I2C register reads . It typically offers 2 degree rms heading accuracy with
proper calibration as well as warm start capability; starting from power on
in a previously calibrated state. It is a relatively low-power solution
providing quaternion updates at the rate of the gyro up to 400 Hz
guaranteed.

Compared to the Sparkfun offering, it is an astounding bargain. So yes, I
would recommend it.

**Comment by MitalPattani** [comment]
Yes the silver coloured pads below which sj2 is written. When you desoldier it you will see 3 rectangular pads, you need to connect one on the centre and right.
