### ISSUE TITLE
Could not connect getting 0x1 instead of 0x71

### ISSUE THREAD

**Issue by raoabhijith** [kriswiner/MPU9250#60]
Hi Kris,

I am currently using your STM32F401 project for my STM32 Nucleo board, and I am getting the below message:

CPU SystemCoreClock is 84000000 Hz
I AM 0x1
I SHOULD BE 0x71
Could not connect to MPU9250:
0x1

When I tried to fix this by changing the condition as 0X1, I got to read the data from the sensor but everything seems to be zeros and nothing is really changing. Please suggest me how to get this working for STM32 Nucleo F401RE. I am using the Mbed compiler.

**Comment by kriswiner** [comment]
You don't have either power to the sensor or have the wrong I2C connections.

**Comment by raoabhijith** [comment]
I have connected SCL and SDA to A4 and A5 pins asnper your comments in the code. And VCC for the board is connected to 3.3V on the board. Do you think something needs to be changed?

**Comment by kriswiner** [comment]
Do you have pullup resistors on SDA and SCL? What is the voltage showing on
SDA and SCL?

-----Original Message-----

**Comment by raoabhijith** [comment]
Without the pull up resistors only I am getting close to 3.3V on SDA and SCL pins Kris.. Not sure what the problem could be :(

**Comment by raoabhijith** [comment]
My final connections with my STM32 nucleo are like this:
VCC - 3.3V
GND - GND
SDA - A4
SCL - A5
ADO - GND
and the I2C address has been changed to x68 since ADO has been given LOW.. I am using this breakout board: 

![image](https://cloud.githubusercontent.com/assets/18704787/14920364/b00d9580-0e4a-11e6-964e-0da310759faa.png)

**Comment by kriswiner** [comment]
I don't know why it is not working. Make sure you are calling A4 and A5 in
your code, and you could try switching A4 and A5, but the board you are
using looks OK. You could try another MPU9250 board.

Or try another MCU like a Teensy.

-----Original Message-----

**Comment by whatnick** [comment]
On the Nucleo the i2c bus is actually not connected to A4-A5. Instead it is on the other side the last 2 pins. Try hooking up the sensor there.

**Comment by whatnick** [comment]
See pinout here - https://developer.mbed.org/platforms/ST-Nucleo-F401RE/#board-pinout. A4-A5 is not linked to i2c.

**Comment by raoabhijith** [comment]
Thank you so much whatnick. It worked now I am able to read the sensor data successfully. Thank you Kris for the suggestions.
